### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by dirtbirb** [sabjorn/NumpySocket#1]
Just putting this in the issue queue in case anyone has an interest in working on it. I'm probably going to implement it in my own fork assuming I know how.

**Comment by vaghawan** [comment]
Hi, I'm interested to work on it. I'm not sure if you already did it though. The code should be mostly workable with the minimal efforts in python3 right? Or Atleast that looks like to me.

**Comment by dirtbirb** [comment]
I did, and then I made it into something suited for my own purposes, so I'm not sure how generally applicable it is... it's still an image server/client though, sending images as numpy arrays that can be interpreted by OpenCV. I can update my current branch if that would be useful. It's currently defunct.

I'm actually quite happy with my image server/client. It has a communication protocol to change settings on the fly, capture raw images, change camera ports (compute module), etc. Also workarounds for annoying stuff like the inability to set analog gain.

**Comment by vaghawan** [comment]
Oh, that's nice. Actually, I worked on it, and get something like this working in the python3 in a much simpler way. It's here if anybody needs: https://github.com/ekbanasolutions/numpy-using-socket

Thanks

**Comment by sabjorn** [comment]
@dirtbirb and @vaghawan 
Apparently the default behaviour of Github is that I am not setup to watch my own repositories so apologies for not seeing this earlier. (I guess a good policy in the future is to tag the repo owner in issues in the future).

I have updated this module for Python3: https://github.com/sabjorn/NumpySocket/releases/tag/v0.2.0

Hopefully this is useful to someone in the future.

**Comment by sabjorn** [comment]
fixed in 6640df5ad403311b7770a73ce90b5ddc97ce7e03

**Comment by vaghawan** [comment]
Great @sabjorn . Thanks
