### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by vilgacx** [sabjorn/NumpySocket#5]
Traceback (most recent call last):
  File "E:\TONY\Paitent\main.py", line 2, in <module>
    from numpysocket import NumpySocket
ModuleNotFoundError: No module named 'numpysocket'

**Comment by sabjorn** [comment]
@CypherX7 
did you run the setup script in this repo?

```
python setup.py install
```

or, as an alternative, you can put `NumpySocket` in this: `E:\TONY\Paitent\` directory and your `main.py` should be able to get access to it

**Comment by vilgacx** [comment]
ya I ran `python setup.py install` and it got successfully installed but I am getting same error while running code

**Comment by vilgacx** [comment]
I will try that alternative method. Thank you

**Comment by sabjorn** [comment]
@CypherX7 I just tried locally and apparently this has been broken for a while. Let me know if the alternative functions.

I will keep this issue around so that I remember to fix it (and then when it's fixed you will get an update).

**Comment by sabjorn** [comment]
## problem

Neither:
```
python setup.py install
```
nor
```
pip install .
```
allows for this module to properly install.

## short term solution
- remove `setup.py` to prevent issue and instruct  in `README.md` to clone repo into project

## long term solution
- reimplement `setup.py` so it works

**Comment by sabjorn** [comment]
@CypherX7 I think I fixed it. Will you test out a new branch for me?

https://github.com/sabjorn/NumpySocket/tree/fix/setup_script

also, do you use `venv`?

**Comment by CypherX7** [comment]
i don't use venv but i will create right no

**Comment by vilgacx** [comment]
I will create it right now

**Comment by vilgacx** [comment]
Okay I will test it right now and put my reviews

**Comment by CypherX7** [comment]
### Same Error
from numpysocket import NumpySocket
ModuleNotFoundError: No module named 'numpysocket'

**Comment by sabjorn** [comment]
@CypherX7 can you please post the commands you are using?
It is also possible you will need to uninstall the previous version of `numpysocket` before trying this new branch since I don't know if the install script will actually take care of this.

**Comment by vilgacx** [comment]
Hey Its working.

**Comment by vilgacx** [comment]
Okay I accidently downloaded the old one instead of latest therefore latest one is working

**Comment by vilgacx** [comment]
Its works like a charm now

**Comment by vilgacx** [comment]
one thing u should try is to send compressed from server side and decompress it on client side.. It will be more better then.

**Comment by vilgacx** [comment]
Okay Thanks Man helping me..

**Comment by sabjorn** [comment]
@CypherX7 compression should be easy enough, `numpy` has a `savez_compressed` method that could be swapped out. However, there will be limits to have effective this compression will be depending on your data.

I could make this optional and allow the user to set compression active. Please write a feature request issue for this if it's something you want.

**Comment by vilgacx** [comment]
okay thanks.


> @CypherX7 compression should be easy enough, `numpy` has a `savez_compressed` method that could be swapped out. However, there will be limits to have effective this compression will be depending on your data.
> 
> I could make this optional and allow the user to set compression active. Please write a feature request issue for this if it's something you want.
