### ISSUE TITLE
disconnects

### ISSUE THREAD

**Issue by amarco** [sabjorn/NumpySocket#7]
Hi When the client is killed  (ctrl c or other method) the server aborts.
Is the server side intrended to stay up and always awaiting new connections?

**Comment by sabjorn** [comment]
Hi @amarco, the server is intended to stay up but taking new connections is not implement (outlined briefly in the [readme](https://github.com/sabjorn/NumpySocket#topology)). 

If you would like this implemented, please write up a detailed description of what you expect with this feature and I’ll try to implemented it as soon as I have time.
